# Generated by Django 4.1.7 on 2023-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0002_alter_packet_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
