# Generated by Django 4.1.7 on 2023-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0003_alter_packet_qr_code'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='user', to='packet.category'),
        ),
    ]
