# Generated by Django 4.1.7 on 2023-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('EMP', 'Employer'), ('POP', 'Population')], default='POP', max_length=50, null=True),
        ),
    ]
