# Generated by Django 4.1.7 on 2023-03-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('EMP', 'Employer'), ('POP', 'Population'), ('ADMIN', 'Admin')], max_length=50, null=True),
        ),
    ]
