# Generated by Django 5.1.4 on 2024-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('EMP', 'Employer'), ('POP', 'Population'), ('ADMIN', 'Admin'), ('AGENT', 'Agent')], max_length=50, null=True),
        ),
    ]
