# Generated by Django 5.2.9 on 2025-12-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('card_number', models.CharField(help_text='Masked card number (e.g., 860006******6311)', max_length=20)),
                ('card_expire', models.CharField(help_text='Card expiry date (MM/YY)', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_recurrent', models.BooleanField(default=False, help_text='Can be used for recurring payments')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payme Card',
                'verbose_name_plural': 'Payme Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(help_text='Payme receipt _id', max_length=100, unique=True)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in tiyin')),
                ('state', models.IntegerField(choices=[(0, 'Yaratilgan'), (1, 'Kutilmoqda'), (2, 'Pending'), (4, "To'langan"), (50, 'Bekor qilingan')], default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('pay_time', models.BigIntegerField(blank=True, null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payme.paymecard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payme_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payme Receipt',
                'verbose_name_plural': 'Payme Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('card_create', 'Card Create'), ('card_verify', 'Card Verify'), ('card_check', 'Card Check'), ('card_remove', 'Card Remove'), ('receipt_create', 'Receipt Create'), ('receipt_pay', 'Receipt Pay'), ('receipt_cancel', 'Receipt Cancel')], max_length=50)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payme_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payme Transaction Log',
                'verbose_name_plural': 'Payme Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
