version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: tozauz_postgres
    environment:
      POSTGRES_DB: tozauz
      POSTGRES_USER: tozauz
      POSTGRES_PASSWORD: tozauz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    restart: unless-stopped
    image: redis:7.2.4
    ports:
      - "6379:6379"
    expose:
      - 6379


volumes:
  postgres_data:
