# Generated by Django 4.1.7 on 2023-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='capital',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
