# Generated by Django 4.1.7 on 2023-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='tarrif',
            field=models.CharField(default='deleted', max_length=200),
            preserve_default=False,
        ),
    ]
