# Generated by Django 4.1.7 on 2023-03-10 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_payout_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
