# Generated by Django 4.1.7 on 2023-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_earning_tarrif'),
    ]

    operations = [
        migrations.AddField(
            model_name='payme',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
