# Generated by Django 4.1.7 on 2023-04-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0003_alter_packet_qr_code'),
        ('ecopacket', '0018_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
        ('bank', '0003_earning_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecopacket.box'),
        ),
        migrations.AddField(
            model_name='earning',
            name='packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packet.packet'),
        ),
    ]
