# Generated by Django 4.1.7 on 2023-04-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0018_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
        ('packet', '0003_alter_packet_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0004_earning_box_earning_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='card_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecopacket.box'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packet.packet'),
        ),
        migrations.CreateModel(
            name='PayMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('card', models.CharField(blank=True, max_length=16, null=True)),
                ('card_name', models.CharField(blank=True, max_length=55, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
