# Generated by Django 4.1.7 on 2023-04-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_payout_card_payout_card_name_alter_earning_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payme_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
