# Generated by Django 4.1.7 on 2024-11-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecopacket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='box',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='box',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='seller_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
