# Generated by Django 5.1.4 on 2024-12-16 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0002_box_cashback_box_is_active_box_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='cashback',
        ),
        migrations.AddField(
            model_name='box',
            name='seller_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='seller_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
