# Generated by Django 5.1.4 on 2024-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0003_remove_box_cashback_box_seller_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='datetime_of_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
