# Generated by Django 5.1.4 on 2024-12-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0004_box_address_box_datetime_of_delivery_box_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='containers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='unloading_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
