# Generated by Django 5.2.5 on 2025-08-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0006_box_fandomat_flaskqrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaskqrcode',
            name='scannered_at',
        ),
        migrations.RemoveField(
            model_name='flaskqrcode',
            name='user',
        ),
    ]
