# Generated by Django 5.2.6 on 2025-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecopacket", "0008_remove_duplicate_barcodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaskqrcode",
            name="bar_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
