# Generated by Django 5.2.8 on 2025-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0009_alter_flaskqrcode_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaskqrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flask_qr_codes/'),
        ),
    ]
