# Generated by Django 5.2.8 on 2025-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0008_alter_flaskqrcode_bar_code'),
        ('ecopacket', '0010_alter_flaskqrcode_bar_code'),
        ('ecopacket', '0011_alter_flaskqrcode_bar_code'),
    ]

    operations = [
    ]
