# Generated by Django 5.2.8 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecopacket", "0012_merge_20251119_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fandomat cashalok balansi. Flask QR kod scan qilinganda bu balansdan pul yechiladi.",
                max_digits=20,
            ),
        ),
    ]
