# Generated by Django 4.1.7 on 2023-03-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
        ('ecopacket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packet.category'),
        ),
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_568a7c38-3605-434a-9435-c6a5a022317f', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_54e4f4c5-ae34-45ed-978d-fa835b1f710f', max_length=50),
        ),
    ]
