# Generated by Django 4.1.7 on 2023-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0002_box_category_box_name_alter_box_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_8b9e16f1-9fdd-4d18-bcee-dd7df4be424c', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_b7489375-fee6-4bb3-9fae-d0a0e1ec1307', max_length=50),
        ),
    ]
