# Generated by Django 4.1.7 on 2023-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0003_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_e7ddb342-9e52-422a-8edd-494f137d1da3', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_9061fbe3-3b4e-442c-b1a0-33045aacc327', max_length=50),
        ),
    ]
