# Generated by Django 4.1.7 on 2023-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0004_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_6f6edec2-77de-434f-89ea-0f6383fe9ce2', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_a4dd6201-66e7-4325-bce3-5e2b0b886bc5', max_length=50),
        ),
    ]
