# Generated by Django 4.1.7 on 2023-03-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0005_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_0cb466b1-99f4-4642-b6fc-c72a9b211b84', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_b24f4129-4c50-4eba-a07b-d6ec0760bbe3', max_length=50),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='ecopacket.box'),
        ),
    ]
