# Generated by Django 4.1.7 on 2023-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0007_alter_box_qr_code_alter_box_sim_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_ba1f17c7-a5e0-4b12-bc01-385ecc689037', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_ba1fc23f-da02-46d5-80b5-59e56880a94e', max_length=50),
        ),
    ]
