# Generated by Django 4.1.7 on 2023-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0008_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_416e155f-d9b5-4c85-82d6-84b124a0c9ae', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_0dc82ace-2af9-4b36-82e9-90261c473069', max_length=50),
        ),
    ]
