# Generated by Django 4.1.7 on 2023-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0009_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_9112da17-8168-4742-bb67-4fbd5af74d15', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_7024d2d4-981b-4182-8eb0-9cf6d567bc9e', max_length=50),
        ),
    ]
