# Generated by Django 4.1.7 on 2023-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0010_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_b118bb29-af09-4518-8765-0be90ac56874', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_aed72621-a940-4016-88fe-5e1a50349d97', max_length=50),
        ),
    ]
