# Generated by Django 4.1.7 on 2023-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0011_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_8303e359-0e37-4dcf-b0e3-679686e158bd', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_07acacec-eff5-462b-a5e3-3040285f66e4', max_length=50),
        ),
    ]
