# Generated by Django 4.1.7 on 2023-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0012_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_e5121fea-b266-43cc-b278-604db5026568', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_14b552f9-cdd7-4451-a220-5fa35aa792f7', max_length=50),
        ),
    ]
