# Generated by Django 4.1.7 on 2023-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopacket', '0013_alter_box_qr_code_alter_ecopacketqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_code',
            field=models.CharField(default='ecobox_226bb142-0fdb-40c4-8730-a5b8bf4ac0c3', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecopacketqrcode',
            name='qr_code',
            field=models.CharField(default='ecopacket_971f232d-84e6-476b-8f7b-c1a38b0f0da7', max_length=50),
        ),
    ]
