# Generated by Django 4.1.7 on 2023-03-02 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='address',
        ),
        migrations.RemoveField(
            model_name='box',
            name='location',
        ),
        migrations.CreateModel(
            name='BoxFillCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('fill_date', models.DateTimeField()),
                ('state', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.box')),
            ],
        ),
    ]
