# Generated by Django 4.1.7 on 2023-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_remove_box_address_remove_box_location_boxfillcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxfillcycle',
            name='fill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
