# Generated by Django 5.1.4 on 2025-05-24 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Uy nomi kamida 2 ta belgidan iborat bo'lishi kerak", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_code', models.CharField(help_text="Uyga qo'shilish uchun taklifnoma kodi", max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_homes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uy',
                'verbose_name_plural': 'Uylar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Uy admin huquqlari')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.home')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Uy a'zoligi",
                'verbose_name_plural': "Uy a'zoliklari",
                'unique_together': {('home', 'user')},
            },
        ),
    ]
