# Generated by Django 5.2.1 on 2025-05-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hudud nomi', max_length=100, unique=True, verbose_name='Hudud nomi')),
                ('code', models.CharField(help_text='Hudud kodi (masalan: TAS-01)', max_length=10, unique=True, verbose_name='Hudud kodi')),
                ('monthly_waste_limit', models.PositiveIntegerField(default=15, help_text='Oylik chiqindi limitsi (paketlar soni)', verbose_name='Oylik chiqindi limitsi')),
                ('description', models.TextField(blank=True, help_text="Hudud haqida qo'shimcha ma'lumot", null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, help_text='Hudud faol holati', verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='home',
            name='region',
            field=models.ForeignKey(help_text="Uy tegishli bo'lgan hudud", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='home.region', verbose_name='Hudud'),
        ),
        migrations.CreateModel(
            name='WasteMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('total_scans', models.PositiveIntegerField(default=0, verbose_name='Jami skanerlangan paketlar')),
                ('total_homes', models.PositiveIntegerField(default=0, verbose_name='Jami uylar soni')),
                ('total_members', models.PositiveIntegerField(default=0, verbose_name="Jami a'zolar soni")),
                ('limit_exceeded', models.BooleanField(default=False, verbose_name='Limit oshirilganmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='home.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Oylik hisobot',
                'verbose_name_plural': 'Oylik hisobotlar',
                'ordering': ['-year', '-month'],
                'unique_together': {('region', 'year', 'month')},
            },
        ),
    ]
