# Generated by Django 5.1.4 on 2024-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_application_comment_application_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('invoice', 'Invoice'), ('card', 'Card')], default='bank_account', max_length=200),
        ),
    ]
