# Generated by Django 5.2.9 on 2025-12-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_application_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('qr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exists', models.BooleanField(default=False)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QR Check Log',
                'verbose_name_plural': 'QR Check Logs',
                'ordering': ['-request_time'],
            },
        ),
    ]
