# Generated by Django 5.2.1 on 2025-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ignore_agent',
            field=models.BooleanField(default=False),
        ),
    ]
