# Generated by Django 5.1.4 on 2025-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0002_category_ignore_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_type',
            field=models.CharField(choices=[('aluminum', 'Aluminum'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('yellow', 'Yellow'), ('black', 'Black'), ('red', 'Red')], default='black', max_length=20),
        ),
    ]
