# Generated by Django 5.2.6 on 2025-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0003_category_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='filter_type',
            field=models.CharField(choices=[('aluminum', 'Aluminum'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('yellow', 'Yellow'), ('black', 'Black'), ('red', 'Red'), ('white', 'White')], default='black', max_length=20),
        ),
    ]
